name: XSJobsMax
version: '${project.version}'
main: net.xsapi.panat.xsjobsmax.core.core
api-version: 1.19
authors: [ PanatXsectorZ ]
description: LimitBreak your jobs skill!!
aliases: xsjobs
softdepend: [Vault, PlayerPoints]
commands:
  xsjobs:
    description: command for xsjobs-max plugin